# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
name: nf-core CI
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false
  NFTEST_VER: "0.8.4"

concurrency:
  group: "{% raw %}${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}{% endraw %}"
  cancel-in-progress: true

jobs:
  test_profile_standard:
    name: nf-test with standard profiles
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
        profile:
          - "test"
          - "test_model_information"
          - "test_mouse_all_pep_lengths"
          - "test_assembly_only"
          - "test_bins_only"
          - "test_coassembly"
          - "test_mhcflurry"
          - "test_mhcnuggets_1"
          - "test_mhcnuggets_2"

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Check out test data
        uses: actions/checkout@v3
        with:
          repository: nf-core/test-datasets
          ref: metapep
          path: test-datasets/
          fetch-depth: 1

      - name: Replace remote paths in samplesheets
        run: |
          for f in ${{ github.workspace }}/test-datasets/samplesheets/v1.0/*.csv; do
            sed -i "s=https://github.com/nf-core/test-datasets/tree/metapep/testdata/=${{ github.workspace }}/test-datasets/=g" $f
            echo "========== $f ============"
            cat $f
            echo "========================================"
          done;

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Disk space cleanup
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash -s $NFTEST_VER
          sudo mv nf-test /usr/local/bin/

      - name: Run nf-test
        run: |
          nf-test test --tag ${{ matrix.profile }} --profile ${{ matrix.profile }},docker --junitxml=test.xml

      - name: Output log on failure
        if: failure()
        run: |
          sudo apt install bat > /dev/null
          batcat --decorations=always --color=always ${{ github.workspace }}/.nf-test/tests/*/output/pipeline_info/software_versions.yml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: "*.xml"

  test_profile_download:
    name: nf-test with profiles needing entrez downloads
    # Only run on PRs from branches of nf-core/metapep repository or on push if this is the nf-core dev branch (merged PRs)
    # (GitHub secrets are not accessible for workflows from forks)
    if: "{% raw %}${{ github.event.pull_request.head.repo.full_name == 'nf-core/metapep' || (github.event_name == 'push' && github.repository == 'nf-core/metapep') }}{% endraw %}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
        tags:
          - "test_all"
          - "test_mouse"
          - "test_taxa_only"
          - "test_taxa_specific_assembly"
        profile:
          - "docker"

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Check out test data
        uses: actions/checkout@v3
        with:
          repository: nf-core/test-datasets
          ref: metapep
          path: test-datasets/
          fetch-depth: 1

      - name: Replace remote paths in samplesheets
        run: |
          for f in ${{ github.workspace }}/test-datasets/samplesheets/v1.0/*.csv; do
            sed -i "s=https://github.com/nf-core/test-datasets/tree/metapep/testdata/=${{ github.workspace }}/test-datasets/=g" $f
            echo "========== $f ============"
            cat $f
            echo "========================================"
          done;

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Disk space cleanup
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash -s $NFTEST_VER
          sudo mv nf-test /usr/local/bin/

      - name: Run nf-test
        env:
          NCBI_EMAIL: ${{ secrets.NCBI_EMAIL }}
          NCBI_KEY: ${{ secrets.NCBI_KEY }}
        run: |
          nf-test test --tag ${{ matrix.profile }} --profile ${{ matrix.profile }},docker --junitxml=test.xml

      - name: Output log on failure
        if: failure()
        run: |
          sudo apt install bat > /dev/null
          batcat --decorations=always --color=always ${{ github.workspace }}/.nf-test/tests/*/output/pipeline_info/software_versions.yml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: "*.xml"
